import Link from 'next/link';
import Image from 'next/image';
import RugTouchControls from './RugTouchControls';
import r from '../../styles/RugExe.module.css';
import {useEffect,useState} from 'react';
import {useGame} from '../../lib/arcade/after-hours/use-game';
import {createRug,stepRug,WEAPONS} from '../../lib/arcade/after-hours/rug-sim.mjs';
import {RUG_LEVELS} from '../../lib/arcade/after-hours/rug-world.mjs';
import s from '../../styles/AfterHours.module.css';
const amount=n=>Math.round(n||0).toLocaleString('en-US');
export default function RugExe(){
 const [level,setLevel]=useState(0),[allTapes,setAllTapes]=useState(false),[ending,setEnding]=useState(2);
 const game=useGame({kind:'rug',create:createRug,step:stepRug,options:{level,allTapes}}),v=game.view,active=game.mode==='playing';
 useEffect(()=>{if(game.mode!=='result'||v?.level!==7||v?.phase!=='complete')return;setEnding(0);const first=setTimeout(()=>setEnding(1),1600),second=setTimeout(()=>setEnding(2),3800);return()=>{clearTimeout(first);clearTimeout(second);};},[game.mode,v?.level,v?.phase]);
 const start=(next=level)=>{setLevel(next);setAllTapes(game.progress?.mall.tapes.length>=9);game.start();};
 const chooseWeapon=i=>{if(game.runtime.current?.state.unlocked.includes(i))game.runtime.current.state.weapon=i;};
 const portfolio=v?.escape?Math.max(4.2,1842993*Math.pow(.992,v.escape)):Math.max(0,(v?.player.hp||0)*1000);
 return <div className={`${s.shell} ${r.rug}`}><header className={s.header}><Link href='/os'><b>TERMINL</b><span>ARCADE</span></Link><span>RUG.EXE / PROTOCOL STILL RUNNING</span><button onClick={()=>game.setMuted(!game.muted)}>{game.muted?'SOUND OFF':'SOUND ON'}</button>{game.mode==='playing'&&<button onClick={game.pause}>PAUSE / HELP</button>}</header><main className={s.viewport}><canvas ref={game.canvas} tabIndex={0} aria-label='RUG.EXE first-person shooter. WASD moves, mouse aims, click fires, Space jumps, Shift dashes, Control slides, E uses controls.'/>
 {v&&game.mode!=='menu'&&<><div className={s.hud}><div><small>PORTFOLIO</small><strong>${amount(portfolio)}</strong><small>COLLATERAL {amount(v.player.armor)}%</small><div className={s.meter}><i style={{width:`${v.player.hp}%`}}/></div></div><div className={s.clock}><small>LEVERAGE</small>{v.leverage}X</div><div className={s.right}><small>{RUG_LEVELS[v.level].name}</small><strong>{amount(v.score)}</strong><small>{Math.floor(v.tick/3600)}:{String(Math.floor(v.tick/60)%60).padStart(2,'0')} · KILLS {v.kills}</small></div></div><div className={s.zone}>{v.escape?'THE RUG · RETURN TO THE ENTRY PORTAL':v.exitOpen?'EXIT OPEN · REACH THE FAR PORTAL':`${v.world.switches.filter(c=>c.used).length}/2 CONTROLS · ${Math.max(0,Math.ceil(v.initialEnemies*.6)-v.kills)} KILLS TO UNLOCK EXIT`}<br/>SECRETS {v.secrets.length}/{v.world.secrets.length}</div><div className={s.crosshair}>+</div><div className={`${s.weapon} ${r.weaponReadout}`}><strong>{WEAPONS[v.weapon].name}</strong>{WEAPONS[v.weapon].ammo?`${amount(WEAPONS[v.weapon].ammo==='armor'?v.player.armor:v.ammo[WEAPONS[v.weapon].ammo])} ${WEAPONS[v.weapon].ammo.toUpperCase()}`:'UNLIMITED'}<br/><small>{v.player.dashCooldown?'DASH RECHARGING':'DASH READY'}</small></div><div className={`${s.weaponBar} ${r.weaponSlots}`}>{v.unlocked.map(i=><button key={i} aria-pressed={v.weapon===i} onClick={()=>chooseWeapon(i)}>{i+1} {WEAPONS[i].name}</button>)}</div>{v.hitFlash>0&&<div className={s.damage}/>} {v.callout?.until>v.tick&&<div className={s.callout} role='status'><b>{v.callout.text}</b><span>{v.callout.detail}</span></div>}{v.nearControl&&active&&<div className={s.secretLink}>E / USE · {v.nearControl}</div>}</>}
 {active&&<><div className={r.weaponArt} data-firing={v?.shotFlash>0}><Image src={`/arcade/rug-exe/${['weapon-0','weapon-1','weapon-2','special-0','special-1','weapon-3','special-2','special-3'][v?.weapon||0]}-v1.webp`} width={512} height={512} unoptimized alt=''/></div><RugTouchControls game={game}/></>}
 {game.mode==='menu'&&<div className={s.overlay}><section className={s.panel}><span className={s.eyebrow}>THE DEV LEFT. THE PROTOCOL DIDN’T.</span><h1>RUG.EXE</h1><p>Move fast. Cut through the bots. Shut the system down.<br/>Build leverage with quick kills. Standing still is expensive.</p><div className={s.levels}>{RUG_LEVELS.map((l,i)=><button key={l.id} aria-pressed={level===i} disabled={i>Math.max(1,game.progress?.rug.unlocked||0)} onClick={()=>setLevel(i)}>{String(i+1).padStart(2,'0')} / {l.name}{i>Math.max(1,game.progress?.rug.unlocked||0)?' 🔒':''}</button>)}</div><p>{RUG_LEVELS[level].subtitle}<br/>{RUG_LEVELS[level].objective}</p><div className={s.options}><label>Graphics<select value={game.quality} onChange={e=>game.setQuality(e.target.value)}><option value='high'>High</option><option value='low'>Low</option></select></label><span>PROGRESS SAVED ON THIS DEVICE</span></div><button className={s.primary} onClick={()=>start()}>ENTER THE PROTOCOL →</button><p className={r.keyHelp}>WASD move · mouse aim · click / F fire · SPACE jump<br/>SHIFT dash · CTRL slide · 1–8 weapons · E use · R retry<br/>Click the arena to capture the mouse. Escape releases it.</p><p className={r.mobileHelp}>Left stick moves. Drag the right side to aim.<br/>Hold FIRE and drag to shoot while aiming. JUMP, DASH, SLIDE and USE sit beside your right thumb.</p><details className={s.records}><summary>LOCAL RECORDS</summary>{game.progress?.rug.records.slice(0,8).map((r,i)=><div key={i}>{RUG_LEVELS[r.level]?.name} / {r.grade} · {amount(r.score)} · {(r.ticks/60).toFixed(1)}s · {r.secrets} secrets</div>)}</details></section></div>}
 {game.mode==='paused'&&<div className={s.overlay}><section className={s.panel}><span className={s.eyebrow}>PROTOCOL SUSPENDED</span><h2>STILL HERE?</h2><p>WASD run / strafe · Mouse aim · Click or F fire<br/>SPACE jump · CTRL crouch / slide · SHIFT dash<br/>1–8 or mouse wheel switch weapons · E activate controls<br/>R restart · F3 collision and AI debug<br/>Controller: left stick moves, right stick aims, A jumps, LT dashes, RT fires. Use on-screen weapon buttons.</p><button className={s.primary} onClick={game.resume}>RESUME →</button><button className={s.secondary} onClick={()=>start(v?.level)}>RETRY LEVEL</button><button className={s.secondary} onClick={game.menu}>LEVEL SELECT</button></section></div>}
 {game.mode==='result'&&v&&ending<2&&v.level===7&&v.phase==='complete'&&<div className={`${s.overlay} ${s.ending}`} role='status'><section className={s.panel}>{ending===0?<h2>FUNDS ARE SAFU.</h2>:<><h2>ILLEGAL OPERATION</h2><p>RUG.EXE has performed an illegal operation and will be shut down.</p></>}</section></div>}
 {game.mode==='result'&&v&&(ending===2||v.level!==7||v.phase!=='complete')&&<div className={s.overlay}><section className={s.panel}><span className={s.eyebrow}>{v.phase==='dead'?'PORTFOLIO: $0':v.level===7?'RUG.EXE HAS PERFORMED AN ILLEGAL OPERATION':'PROTOCOL SEGMENT CLOSED'}</span><h2>{v.phase==='dead'?'LIQUIDATED.':v.level===7?'FUNDS ARE SAFU.':`GRADE ${v.grade}`}</h2>{v.level===7&&v.phase==='complete'&&<p>RUG.EXE has performed an illegal operation and will be shut down.<br/>The corrupted board is now available in MALL RAT.</p>}<dl className={s.stats}>{[['SCORE',amount(v.score)],['TIME',`${(v.tick/60).toFixed(1)}s`],['KILLS',v.kills],['MAX LEVERAGE',`${v.maxLeverage}X`],['ACCURACY',`${Math.min(100,Math.round(v.hits/Math.max(1,v.shots)*100))}%`],['SECRETS',`${v.secrets.length}/${v.world.secrets.length}`],['PORTFOLIO',`$${amount(v.player.hp*1000)}`],['DAMAGE TAKEN',amount(v.damageTaken*1000)]].map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value}</dd></div>)}</dl>{v.phase==='complete'&&v.level<7&&<button className={s.primary} onClick={()=>start(v.level+1)}>NEXT SEGMENT →</button>}<button className={v.phase==='dead'?s.primary:s.secondary} onClick={()=>start(v.level)}>RUN IT AGAIN →</button><button className={s.secondary} onClick={game.menu}>LEVEL SELECT</button>{game.notice&&<p>{game.notice}</p>}</section></div>}
 {game.debug&&v&&<pre className={s.debug}>TICK {v.tick} / POS {v.player.x.toFixed(1)}, {v.player.y.toFixed(1)}, {v.player.z.toFixed(1)}<br/>AI {v.enemies.filter(e=>e.hp>0).length} / SHOTS {v.projectiles.length} / HAZARDS {v.hazards.length}<br/>KILLS {v.kills} / CHAIN {v.chain} / LAST {v.lastKill}<br/>SPAWN {v.world.spawn.x}, {v.world.spawn.z}</pre>}{game.error&&<div className={s.error}>{game.error}<p><Link href='/os'>BACK TO ARCADE</Link></p></div>}</main><footer className={s.controls}>WASD MOVE · MOUSE AIM · CLICK FIRE · SPACE JUMP · CTRL SLIDE · SHIFT DASH · E USE · 1–8 WEAPONS · R RETRY</footer></div>;
}
