const MAP={KeyW:'forward',ArrowUp:'forward',KeyS:'back',ArrowDown:'back',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right',Space:'jump',KeyJ:'flip',KeyK:'grab',KeyL:'grind',KeyM:'manual',KeyE:'interact',KeyQ:'special',KeyB:'bank',KeyC:'turn',KeyX:'bail',ShiftLeft:'dash',ShiftRight:'dash',ControlLeft:'crouch',KeyF:'fire',KeyV:'wallride'};
export function attachInput(canvas,{pause,restart,debug,kind}){
 const held={},pressed={},pointers=new Map();let stick=null,lookX=0,lookY=0,weapon=null,pointerX=0,pointerY=0,dragging=false;
 const clear=()=>{for(const key of Object.keys(held))delete held[key];pointers.clear();for(const key of Object.keys(pressed))delete pressed[key];stick=null;lookX=lookY=0;dragging=false;};
 const key=e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||e.metaKey)return;const down=e.type==='keydown';if(MAP[e.code]){e.preventDefault();held[e.code]=down;}if(down&&!e.repeat){if(e.code==='Escape'){clear();pause();}if(e.code==='KeyR'){clear();restart();}if(e.code==='F3'){e.preventDefault();debug();}if(/^Digit[1-8]$/.test(e.code))weapon=Number(e.code.slice(5))-1;}};
 const pointer=e=>{if(kind==='rug'&&e.pointerType!=='touch'&&document.pointerLockElement!==canvas)canvas.requestPointerLock?.()?.catch?.(()=>{});if(kind==='rug')held.Mouse=true;pointerX=e.clientX;pointerY=e.clientY;dragging=true;};
 const move=e=>{if(kind!=='rug')return;if(document.pointerLockElement===canvas){lookX+=e.movementX;lookY+=e.movementY;}else if(dragging){lookX+=e.clientX-pointerX;lookY+=e.clientY-pointerY;pointerX=e.clientX;pointerY=e.clientY;}};
 const up=()=>{held.Mouse=false;dragging=false;};const blur=()=>{clear();pause(true);};const hidden=()=>{if(document.hidden)blur();};const locked=()=>{if(kind==='rug'&&!document.pointerLockElement)blur();};
 const wheel=e=>{e.preventDefault();weapon={delta:e.deltaY>0?1:-1};};
 window.addEventListener('keydown',key);window.addEventListener('keyup',key);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',hidden);document.addEventListener('pointerlockchange',locked);canvas.addEventListener('pointerdown',pointer);window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);window.addEventListener('pointercancel',up);canvas.addEventListener('wheel',wheel,{passive:false});
 return {clear,stick(value){stick=value;},look(x,y){lookX+=x;lookY+=y;},touch(action,active,id=action){if(active){pointers.set(id,action);if(['action','jump','flip','grab','bank','special','dash','interact','turn','bail'].includes(action))pressed[action]=true;}else pointers.delete(id);},read(){const result={...pressed};for(const key of Object.keys(pressed))delete pressed[key];for(const [code,down]of Object.entries(held))if(down)result[code==='Mouse'?'fire':MAP[code]]=true;for(const action of pointers.values())result[action]=true;if(kind==='mall'&&stick){result.steer=stick.x;result.forward=stick.y<.45;result.back=stick.y>=.45;result.manual=!result.back;result.grind=!result.back;result.touchAssist=true;}if(kind==='rug'&&stick){result.moveX=stick.x;result.moveY=-stick.y;}const pad=navigator.getGamepads?.()?.find(p=>p?.connected);if(pad){const b=i=>pad.buttons[i]?.pressed;result.forward||=pad.axes[1]<-.2;result.back||=pad.axes[1]>.2;result.left||=pad.axes[0]<-.2;result.right||=pad.axes[0]>.2;result.jump||=b(0);result.flip||=b(2);result.grab||=b(1);result.grind||=b(3);result.manual||=b(4);result.special||=b(5);result.interact||=b(2);result.crouch||=b(1);result.fire||=b(7);result.dash||=b(6);if(kind==='rug'){lookX+=(Math.abs(pad.axes[2])>.15?pad.axes[2]:0)*15;lookY+=(Math.abs(pad.axes[3])>.15?pad.axes[3]:0)*10;}}result.lookX=lookX;result.lookY=lookY;result.weapon=weapon;lookX=lookY=0;weapon=null;return result;},dispose(){clear();window.removeEventListener('keydown',key);window.removeEventListener('keyup',key);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',hidden);document.removeEventListener('pointerlockchange',locked);canvas.removeEventListener('pointerdown',pointer);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);window.removeEventListener('pointercancel',up);canvas.removeEventListener('wheel',wheel);}};
}
