import {milestones,medalFor} from './mall-awards.mjs';
export const SAVE_KEY='terminl:after-hours:v1';
const blank=()=>({version:1,mall:{records:[],bests:{},tapes:[],gaps:[],milestones:[],routes:{},ghost:null},rug:{unlocked:0,completed:false,records:[]}});
export function readProgress(storage){try{const v=JSON.parse(storage.getItem(SAVE_KEY));if(v?.version!==1)return blank();const b=blank();b.mall.records=Array.isArray(v.mall?.records)?v.mall.records.filter(r=>r&&Number.isFinite(r.score)&&Number.isFinite(r.longestCombo)&&typeof r.character==='string').slice(0,12):[];b.mall.bests=Object.fromEntries(Object.entries(v.mall?.bests||{}).filter(([key,value])=>['score','damage','longestCombo','maxMultiplier','biggestBail','fastestChallenge'].includes(key)&&Number.isFinite(value)&&value>=0));b.mall.tapes=Array.isArray(v.mall?.tapes)?v.mall.tapes.filter(x=>typeof x==='string').slice(0,9):[];b.mall.gaps=Array.isArray(v.mall?.gaps)?v.mall.gaps.filter(x=>typeof x==='string').slice(0,30):[];b.mall.milestones=Array.isArray(v.mall?.milestones)?v.mall.milestones.filter(x=>typeof x==='string').slice(0,20):[];b.mall.routes=Object.fromEntries(Object.entries(v.mall?.routes||{}).filter(([k,t])=>['outer','concourse'].includes(k)&&Number.isFinite(t)&&t>0));b.mall.ghost=Array.isArray(v.mall?.ghost)&&v.mall.ghost.length<=2000&&v.mall.ghost.every(f=>Array.isArray(f)&&f.length===5&&f.every(Number.isFinite))?v.mall.ghost:null;b.rug.unlocked=Math.max(0,Math.min(7,Math.floor(Number(v.rug?.unlocked)||0)));b.rug.completed=v.rug?.completed===true;b.rug.records=Array.isArray(v.rug?.records)?v.rug.records.filter(r=>r&&Number.isFinite(r.score)&&Number.isInteger(r.level)&&r.level>=0&&r.level<8&&Number.isFinite(r.ticks)).slice(0,40):[];return b;}catch{return blank();}}
export function recordRun(progress,s,storage){const next=structuredClone(progress);if(s.kind==='mall'){
 next.mall.gaps=[...new Set([...(next.mall.gaps||[]),...(s.gaps||[])])];next.mall.milestones=[...new Set([...(next.mall.milestones||[]),...milestones(s)])];next.mall.routes??={};for(const r of s.routesCompleted||[])next.mall.routes[r.id]=Math.min(next.mall.routes[r.id]??Infinity,r.seconds);
 next.mall.tapes=[...new Set([...next.mall.tapes,...s.tapes])];if(s.phase==='finished'&&!s.practice){const record={score:s.score,damage:s.damage,longestCombo:s.stats.longestCombo,maxMultiplier:s.stats.maxMultiplier,biggestBail:s.stats.biggestBail,fastestChallenge:Math.min(...Object.values(s.challengeTimes),Infinity)/60,character:s.character,medal:medalFor(s.score),gaps:s.gaps?.length||0};for(const key of ['score','damage','longestCombo','maxMultiplier','biggestBail'])next.mall.bests[key]=Math.max(next.mall.bests[key]||0,record[key]);if(Number.isFinite(record.fastestChallenge))next.mall.bests.fastestChallenge=Math.min(next.mall.bests.fastestChallenge??Infinity,record.fastestChallenge);if(s.score>=(next.mall.records[0]?.score||0))next.mall.ghost=s.ghost;next.mall.records=[...next.mall.records,record].sort((a,b)=>b.score-a.score).slice(0,12);}}
 else if(s.phase==='complete'){next.rug.unlocked=Math.max(next.rug.unlocked,Math.min(7,s.level+1));next.rug.completed||=s.level===7;next.rug.records=[{level:s.level,score:s.score,ticks:s.tick,grade:s.grade,secrets:s.secrets.length},...next.rug.records].slice(0,40);}
 let saved=true;try{storage.setItem(SAVE_KEY,JSON.stringify(next));}catch{saved=false;}return {progress:next,saved};}
