import {distance,lineBlocked,angleDelta,floorAt,clamp,moveSolid,inside} from './math.mjs';
import {spawnEnemy} from './rug-world.mjs';
export const WEAPONS=[{name:'PAPER HANDS',role:'Accurate fallback · unlimited',cooldown:14,damage:22,range:60,spread:.075,ammo:null},{name:'SLIPPAGE',role:'Close-range burst',cooldown:38,damage:130,range:22,spread:.28,ammo:'shells',cost:1},{name:'GAS BURNER',role:'Hold fire · GWEI',cooldown:4,damage:12,range:11,spread:.4,ammo:'gwei',cost:2},{name:'LIQUIDATION CANNON',role:'Splash · costs collateral',cooldown:60,damage:180,range:50,ammo:'armor',cost:12},{name:'AIRDROP',role:'Delayed area strike',cooldown:75,damage:240,range:25,ammo:'crates',cost:1},{name:'MEV',role:'Reflect nearby projectiles',cooldown:48,damage:0,range:15,ammo:'gwei',cost:15},{name:'THE BAG',role:'Melee · strong knockback',cooldown:24,damage:70,range:3.8,spread:.7,ammo:null},{name:'EXIT LIQUIDITY',role:'Vortex · emergency escape',cooldown:100,damage:500,range:18,ammo:'ultimate',cost:1}];
export const LEVERAGE=[1,2,5,10,25,50,100];
export function hurtPlayer(s,damage){const p=s.player;if(p.invuln>0||s.phase!=='playing')return;const absorbed=Math.min(p.armor,damage*.65);p.armor-=absorbed;const actual=(damage-absorbed)*(s.leverage===100?1.12:1);p.hp=Math.max(0,p.hp-actual);p.invuln=16;s.damageTaken+=actual;s.hitFlash=12;s.events.push({type:'hurt'});if(p.hp<=0){s.phase='dead';s.callout={text:'LIQUIDATED',detail:'R to retry. Keep moving.',until:s.tick+99999};}}
export function damageEnemy(s,e,damage){if(e.hp<=0)return;e.hp-=damage;e.hit=8;
 if(e.type==='sybil'&&!e.split&&e.hp>0){e.split=true;for(let i=0;i<2;i++){const child=spawnEnemy('bot',e.x+(i?1.5:-1.5),e.z+1,s.nextEnemy++,e.y);child.hp=20;child.color='#be92d0';s.enemies.push(child);}}
 if(e.hp<=0){s.kills++;s.chain=s.tick-s.lastKill<240?s.chain+1:1;s.lastKill=s.tick;s.leverage=LEVERAGE[Math.min(6,Math.floor(s.chain/3))];s.maxLeverage=Math.max(s.maxLeverage,s.leverage);s.score+=Math.round((e.type==='whale'?600:100)*s.leverage);s.events.push({type:'kill'});if(s.kills%3===0&&s.world.pickups.length<120)s.world.pickups.push({id:`drop-${e.id}`,type:'health',x:e.x,z:e.z,y:e.y,amount:8+Math.min(12,s.leverage)});}
}
export function fireWeapon(s){const p=s.player,w=WEAPONS[s.weapon];if(p.fireCooldown>0)return false;const resource=w.ammo==='armor'?p.armor:s.ammo[w.ammo];if(w.ammo&&resource<w.cost){s.callout={text:'EMPTY',detail:'Switch to PAPER HANDS (1) or THE BAG (7).',until:s.tick+60};p.fireCooldown=10;return false;}if(w.ammo==='armor')p.armor-=w.cost;else if(w.ammo)s.ammo[w.ammo]-=w.cost;p.fireCooldown=w.cooldown;s.shotFlash=5;s.shots++;s.events.push({type:'shot'});
 const origin={x:p.x,y:p.y+(p.crouch?.75:1.65),z:p.z};
 if(s.weapon===3){s.projectiles.push({x:p.x-Math.sin(p.yaw)*.7,y:origin.y,z:p.z-Math.cos(p.yaw)*.7,vx:-Math.sin(p.yaw)*20,vz:-Math.cos(p.yaw)*20,vy:Math.sin(p.pitch)*20,life:160,owner:'player',rocket:true,damage:w.damage});return true;}
 if(s.weapon===4){const aim={x:p.x-Math.sin(p.yaw)*12,z:p.z-Math.cos(p.yaw)*12};s.hazards.push({...aim,y:floorAt(s.world,aim.x,aim.z),radius:6,delay:60,life:65,friendly:true,damage:w.damage});return true;}
 if(s.weapon===5){let count=0;for(const b of s.projectiles)if(b.owner!=='player'&&distance(p,b)<15){const e=s.enemies.find(e=>e.hp>0&&!lineBlocked(b,e,s.world.solids));if(e){const d=Math.max(1,distance(b,e));b.vx=(e.x-b.x)/d*28;b.vz=(e.z-b.z)/d*28;b.owner='player';b.damage=75;b.vy=(e.y+1-b.y)/d*28;count++;}}s.callout={text:'FRONT RUN',detail:`${count} projectiles redirected`,until:s.tick+60};return true;}
 if(s.weapon===7){for(const e of s.enemies)if(e.hp>0&&distance(p,e)<18&&!lineBlocked(origin,{...e,y:e.y+1},s.world.solids))damageEnemy(s,e,w.damage);p.x=s.world.spawn.x;p.z=s.world.spawn.z;p.y=s.world.spawn.y;s.callout={text:'THANKS FOR PLAYING',detail:'Exit liquidity collected.',until:s.tick+120};return true;}
 const targets=s.enemies.filter(e=>e.hp>0).map(e=>({e,d:distance(p,e),angle:Math.abs(angleDelta(Math.atan2(-(e.x-p.x),-(e.z-p.z)),p.yaw))})).filter(({e,d,angle})=>d<w.range&&angle<w.spread+.5/Math.max(1,d)&&Math.abs(Math.atan2(e.y+1.1-origin.y,d)-p.pitch)<.18+1/Math.max(1,d)&&!lineBlocked(origin,{...e,y:e.y+1},s.world.solids)).sort((a,b)=>a.d-b.d);
 for(const {e,d}of targets.slice(0,s.weapon===0?1:99)){damageEnemy(s,e,w.damage*(s.weapon===1?Math.max(.12,1-d/24):1));s.hits++;if(s.weapon===6){moveSolid(e,-Math.sin(p.yaw)*3,-Math.cos(p.yaw)*3,s.world.solids,.6);}}
 if(s.weapon===1&&targets.some(t=>t.d<5))s.callout={text:'PRICE IMPACT',detail:'Point blank.',until:s.tick+40};
 // Purple panels respond to direct hits and reveal a useful weapon cache.
 for(const secret of s.world.secrets)if(secret.method==='shoot'&&!s.secrets.includes(secret.id)&&distance(p,secret)<40&&Math.abs(angleDelta(Math.atan2(-(secret.x-p.x),-(secret.z-p.z)),p.yaw))<.09&&!lineBlocked(origin,{...secret,y:secret.y+1},s.world.solids))openSecret(s,secret);
 return true;
}
export function openSecret(s,secret){if(secret.open)return;secret.open=true;const panel=s.world.solids.find(b=>b.id===secret.panelId);if(panel)panel.broken=true;s.callout={text:'PASSAGE OPEN',detail:'Something is behind the false wall.',until:s.tick+120};s.events.push({type:'secret'});}
export function discover(s,secret){if(s.secrets.includes(secret.id))return;s.secrets.push(secret.id);s.score+=2000;s.ammo.crates+=2;s.ammo.ultimate=Math.min(3,s.ammo.ultimate+1);s.unlocked=[...new Set([...s.unlocked,4,7])];s.events.push({type:'secret'});s.callout={text:'SECRET FOUND',detail:`${s.secrets.length} / ${s.world.secrets.length} · Unusual weapons recovered`,until:s.tick+180};}
export function explode(s,b){for(const e of s.enemies)if(e.hp>0&&distance(e,b)<7&&!lineBlocked({...b,y:b.y||1},{...e,y:e.y+1},s.world.solids))damageEnemy(s,e,b.damage*(1-distance(e,b)/9));if(distance(s.player,b)<6){hurtPlayer(s,25*(1-distance(s.player,b)/7));s.player.vy=Math.max(s.player.vy,10);s.player.grounded=false;}s.events.push({type:'smash'});}
export function stepEnemies(s){const p=s.player,dt=1/60;
 for(const e of [...s.enemies]){if(e.hp<=0)continue;for(const b of s.world.solids)if(!b.broken&&inside(e,b,.6)){const left=b.x-b.w/2-.65,right=b.x+b.w/2+.65,front=b.z-b.d/2-.65,back=b.z+b.d/2+.65;const exits=[{axis:'x',value:left,d:Math.abs(e.x-left)},{axis:'x',value:right,d:Math.abs(e.x-right)},{axis:'z',value:front,d:Math.abs(e.z-front)},{axis:'z',value:back,d:Math.abs(e.z-back)}].sort((a,b)=>a.d-b.d);e[exits[0].axis]=exits[0].value;}const d=distance(e,p),visible=!lineBlocked({...e,y:e.y+1.5},{...p,y:p.y+1},s.world.solids);e.y=floorAt(s.world,e.x,e.z);e.cooldown--;if(e.hit>0)e.hit--;const buff=s.enemies.some(a=>a.hp>0&&a.type==='influencer'&&distance(a,e)<12)?1.3:1;
  if(e.cooldown<=30&&visible&&d<40){if(e.telegraph===0)s.events.push({type:'warning'});e.telegraph=30-e.cooldown;}
  if(d>2&&d<48){const away=e.type==='manager'&&d<12?-1:1;const speed=e.type==='sniper'&&d>15?0:e.speed*buff;const dx=(p.x-e.x)/d*speed*dt*away,dz=(p.z-e.z)/d*speed*dt*away;if(!s.world.solids.some(b=>!b.broken&&Math.abs(e.x+dx-b.x)<b.w/2+.5&&Math.abs(e.z+dz-b.z)<b.d/2+.5)){e.x+=dx;e.z+=dz;}}
  if(e.cooldown<=0&&visible&&d<42){e.cooldown=e.type==='sniper'?160:e.type==='whale'?200:100;e.telegraph=0;
   if(e.type==='moderator')s.hazards.push({x:p.x,z:p.z,y:p.y,radius:3,delay:45,life:220,damage:12});
   else if(e.type==='whale')s.hazards.push({x:e.x,z:e.z,y:e.y,radius:9,delay:45,life:75,damage:24,slam:true});
   else if(e.type==='manager'&&s.enemies.filter(a=>a.hp>0).length<55)s.enemies.push(spawnEnemy('bot',e.x+1,e.z,s.nextEnemy++,e.y));
   else{const speed=e.type==='sniper'?37:14;s.projectiles.push({x:e.x,y:e.y+1.3,z:e.z,vx:(p.x-e.x)/d*speed,vz:(p.z-e.z)/d*speed,vy:((p.y+1)-(e.y+1.3))/d*speed,damage:e.damage*buff,life:240,owner:'enemy'});}}
  if(d<1.25)hurtPlayer(s,e.damage);
 }
 s.projectiles=s.projectiles.filter(b=>{b.life--;b.x+=b.vx*dt;b.y+=b.vy*dt;b.z+=b.vz*dt;let remove=b.life<=0||b.y<floorAt(s.world,b.x,b.z)||s.world.solids.some(o=>!o.broken&&b.y>o.y&&b.y<o.y+o.h&&Math.abs(b.x-o.x)<o.w/2&&Math.abs(b.z-o.z)<o.d/2);
  if(b.owner==='enemy'&&distance(b,p)<.65&&Math.abs(b.y-(p.y+.8))<1){hurtPlayer(s,b.damage);remove=true;}
  if(b.owner==='player'){const e=s.enemies.find(e=>e.hp>0&&distance(e,b)<1&&Math.abs(e.y+1-b.y)<1.8);if(e){if(!b.rocket)damageEnemy(s,e,b.damage);remove=true;}}
  if(remove&&b.rocket)explode(s,b);return !remove;
 }).slice(-128);
 s.hazards=s.hazards.filter(h=>{h.life--;h.delay--;if(h.delay===0&&h.friendly){for(const e of s.enemies)if(e.hp>0&&distance(h,e)<h.radius)damageEnemy(s,e,h.damage);s.events.push({type:'smash'});}if(!h.friendly&&h.delay<=0&&distance(p,h)<h.radius&&p.y<h.y+1){hurtPlayer(s,h.damage);if(h.slam){p.vy=9;p.grounded=false;}}return h.life>0;}).slice(-12);
}
