import * as THREE from 'three';
import {SKATERS} from './mall-world.mjs';
const C={mint:0x9bffc4,cyan:0x73dfde,amber:0xffb86b,pink:0xed8aca};
export class AfterHoursScene{
 constructor(canvas,state,{quality='high',reducedMotion=false}={}){
  this.canvas=canvas;this.reducedMotion=reducedMotion;this.renderer=new THREE.WebGLRenderer({canvas,antialias:false,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(quality==='low'?.65:Math.min(devicePixelRatio,1.5));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(state.kind==='mall'?0x182329:0x08151a);this.scene.fog=new THREE.Fog(this.scene.background,32,state.kind==='mall'?120:90);this.camera=new THREE.PerspectiveCamera(70,1,.08,180);this.labels=[];this.materials=new Map();this.dynamic=new Map();this.disposables=[];this.geometries=new Map();
  this.ambient=new THREE.HemisphereLight(0xc9deee,0x465548,2);this.scene.add(this.ambient);const sun=new THREE.DirectionalLight(0xffe0c4,2.1);sun.position.set(-20,40,10);this.scene.add(sun);this.sun=sun;this.root=new THREE.Group();this.scene.add(this.root);this.build(state);this.resize();
 }
 mat(color,emissive=false){const key=`${color}-${emissive}`;if(!this.materials.has(key))this.materials.set(key,new THREE.MeshLambertMaterial({color,emissive:emissive?color:0,emissiveIntensity:emissive?.55:0,flatShading:true}));return this.materials.get(key);}
 geometry(type){if(!this.geometries.has(type))this.geometries.set(type,type==='sphere'?new THREE.IcosahedronGeometry(1,0):type==='cylinder'?new THREE.CylinderGeometry(1,1,1,8):type==='cone'?new THREE.ConeGeometry(1,1,6):new THREE.BoxGeometry(1,1,1));return this.geometries.get(type);}
 mesh(parent,x,y,z,w,h,d,color,type='box',glow=false){const m=new THREE.Mesh(this.geometry(type),this.mat(color,glow));m.position.set(x,y,z);m.scale.set(w,h,d);parent.add(m);return m;}
 label(parent,text,x,y,z,color='#b8ffd5',scale=1){const c=document.createElement('canvas');c.width=512;c.height=96;const ctx=c.getContext('2d');ctx.fillStyle='#07100feb';ctx.fillRect(0,0,512,96);ctx.strokeStyle=color;ctx.strokeRect(2,2,508,92);ctx.fillStyle=color;ctx.font='bold 30px monospace';ctx.textAlign='center';ctx.fillText(text,256,58,480);const texture=new THREE.CanvasTexture(c);texture.magFilter=THREE.NearestFilter;this.disposables.push(texture);const material=new THREE.SpriteMaterial({map:texture});this.disposables.push(material);const sprite=new THREE.Sprite(material);sprite.position.set(x,y,z);sprite.scale.set(10*scale,1.875*scale,1);parent.add(sprite);this.labels.push(sprite);return sprite;}
 floor(f){const rise=f.rise||0,a=f.z-f.d/2,b=f.z+f.d/2,l=f.x-f.w/2,r=f.x+f.w/2,y=f.y;const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute([l,y,a,l,y+rise,b,r,y,a,r,y,a,l,y+rise,b,r,y+rise,b],3));g.computeVertexNormals();this.disposables.push(g);const m=new THREE.Mesh(g,this.mat(f.color||'#54636a'));this.root.add(m);if(f.id)this.dynamic.set(f.id,m);if(!rise){for(let x=l+4;x<r;x+=8)this.mesh(this.root,x,y+.008,f.z,.035,.01,f.d,'#657879');for(let z=a+4;z<b;z+=8)this.mesh(this.root,f.x,y+.01,z,f.w,.01,.035,'#657879');}}
 build(s){
  for(const f of s.world.floors)this.floor(f);
  for(const b of s.world.solids){const mesh=this.mesh(this.root,b.x,(b.y||0)+b.h/2,b.z,b.w,b.h,b.d,b.color||'#34424b');if(b.id)this.dynamic.set(b.id,mesh);}
  for(const label of s.world.labels||[])this.label(this.root,label.text,label.x,label.y,label.z,label.color);
  if(s.kind==='mall')this.buildMall(s);else this.buildRug(s);
  this.debug=new THREE.Group();this.scene.add(this.debug);for(const b of s.world.solids){const box=new THREE.Box3(new THREE.Vector3(b.x-b.w/2,b.y||0,b.z-b.d/2),new THREE.Vector3(b.x+b.w/2,(b.y||0)+b.h,b.z+b.d/2));const helper=new THREE.Box3Helper(box,0xffff00);this.disposables.push(helper.geometry,helper.material);this.debug.add(helper);}this.debug.visible=false;
 }
 buildMall(s){
  for(const zone of s.world.zones){
   const trim=zone.id==='arcade'?C.pink:zone.id==='food'?C.amber:C.cyan;
   for(const side of [-1,1]){this.mesh(this.root,zone.x+side*23.4,zone.y+2.8,zone.z-6,.1,3,18,'#44606c');this.mesh(this.root,zone.x+side*23.3,zone.y+4.6,zone.z-6,.1,.12,23,trim,'box',true);}
   this.mesh(this.root,zone.x,zone.y+8,zone.z-24,48,.5,1.4,'#3f5056');
   for(const x of [-24,24]){this.mesh(this.root,zone.x+x,zone.y+5,zone.z-24,1.2,10,1.2,'#697273');this.mesh(this.root,zone.x+x,zone.y+8,zone.z,1, .15,38,C.cyan,'box',true);}this.mesh(this.root,zone.x,zone.y+.02,zone.z-23,46,.04,1,zone.id==='arcade'?C.pink:C.amber);}
  for(const r of s.world.rails){const dx=r.bx-r.x,dz=r.bz-r.z,len=Math.hypot(dx,dz),m=this.mesh(this.root,(r.x+r.bx)/2,r.y,(r.z+r.bz)/2,.17,.17,len,C.cyan,'box',true);m.rotation.y=Math.atan2(dx,dz);for(let i=0;i<=Math.floor(len/6);i++){const t=i/Math.floor(len/6);this.mesh(this.root,r.x+dx*t,r.y/2,r.z+dz*t,.12,r.y,.12,'#728585');}}
  this.mesh(this.root,-79,.025,79,10,.05,10,'#629760');for(let i=0;i<4;i++){this.mesh(this.root,-82+i*2,.6,81,1.5,1.4,1.5,'#588265','cone');}
  this.mesh(this.root,0,.4,0,6,.8,6,'#74868a','cylinder');this.mesh(this.root,0,.85,0,5.3,.08,5.3,'#69cabf','cylinder',true);this.mesh(this.root,0,1.6,0,1.2,2.1,1.2,'#aab7b3','cylinder');
  for(const o of s.world.props){const group=new THREE.Group();group.position.set(o.x,o.y,o.z);this.root.add(group);this.dynamic.set(o.id,group);if(/RUMBLE|LAMBO|MOON|RUG.EXE|CRT/.test(o.kind)){this.mesh(group,0,1,0,1.5,2,1.2,'#282c45');this.mesh(group,0,1.7,.64,1.1,.85,.1,o.color,'box',true);this.mesh(group,0,1,.8,1.5,.2,.7,'#556778');this.label(group,o.kind,0,2.6,0,'#a6ffba',.28);}else if(o.kind==='car'){this.mesh(group,0,.6,0,3,1,1.8,o.color);this.mesh(group,0,1.3,0,1.6,.8,1.6,'#486873');for(const x of [-1,1])for(const z of [-.9,.9])this.mesh(group,x,.35,z,.4,.4,.3,'#161d24','sphere');}else if(/bench|table|counter/.test(o.kind)){this.mesh(group,0,.9,0,o.w,.18,o.d,o.color);for(const x of [-o.w*.35,o.w*.35])for(const z of [-o.d*.3,o.d*.3])this.mesh(group,x,.45,z,.16,.9,.16,'#54615f');if(o.kind==='bench')this.mesh(group,0,1.5,-.5,o.w,.65,.12,'#d8af86');}else if(o.kind==='planter'){this.mesh(group,0,.5,0,1.2,1,1.2,'#bca697','cylinder');this.mesh(group,0,1.5,0,1,1.5,1,'#6b9d76','cone');}else if(o.kind==='mannequin'){this.mesh(group,0,.9,0,.4,1.7,.5,'#d8cba7');this.mesh(group,0,2,0,.38,.38,.38,'#e2d3b1','sphere');}else{this.mesh(group,0,o.h/2,0,o.w,o.h,o.d,o.color);this.mesh(group,0,o.h+.05,0,o.w+.15,.12,o.d+.15,'#c9bfa6');if(/sign|poster|server|vending/.test(o.kind))this.label(group,o.kind.toUpperCase(),0,o.h+1,0,'#ffcf97',.42);}}
  for(const t of s.world.tapes){const g=new THREE.Group();g.position.set(t.x,t.y,t.z);this.mesh(g,0,0,0,.9,.55,.22,'#e998fa','box',true);this.mesh(g,0,0,.13,.65,.2,.04,'#212b3b');this.root.add(g);this.dynamic.set(`tape-${t.id}`,g);}
  this.skater=this.makeSkater(s.character);if(s.board!=='classic')this.skater.children[0].material=this.mat({vhs:'#c48bed',mint:'#abffda',corrupt:'#cdff4a'}[s.board]||'#ffad65',true);this.scene.add(this.skater);this.ghost=this.makeSkater(s.character);this.ghost.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.transparent=true;o.material.opacity=.22;this.disposables.push(o.material);}});this.scene.add(this.ghost);this.ghost.visible=false;
  this.guards=[];for(let i=0;i<6;i++){const g=this.makeSkater('security');if(i>=3){this.mesh(g,0,.6,0,1.8,.8,2.8,'#536e8c');this.mesh(g,0,2.7,0,2,.15,3,'#c7d8cf');for(const x of [-.9,.9])for(const z of [-.9,.9])this.mesh(g,x,.35,z,.35,.35,.35,'#20282b','sphere');}g.visible=false;this.scene.add(g);this.guards.push(g);}this.gate=this.mesh(this.root,0,1,28,36,2,.3,'#ff915e');this.gate.visible=false;this.eventActors=[];for(let i=0;i<9;i++){const actor=this.makeSkater(i===0?'pigeon':'security');this.scene.add(actor);actor.visible=false;this.eventActors.push(actor);}const bull=this.eventActors[0];bull.clear();this.mesh(bull,0,1,0,.65,.7,1.1,'#946951','sphere');this.mesh(bull,0,1.1,-.65,.45,.5,.45,'#694938','sphere');for(const x of [-.4,.4]){this.mesh(bull,x,1.5,-.65,.12,.5,.12,'#dacfa9','cone');for(const z of [-.4,.4])this.mesh(bull,x,.5,z,.15,.8,.15,'#634a39');}this.rugHole=this.mesh(this.root,0,.07,-40,22,.04,8,'#020509');this.rugHole.visible=false;this.particles=[];for(let i=0;i<32;i++){const m=this.mesh(this.scene,0,-100,0,.14,.14,.14,C.amber);m.visible=false;this.particles.push({mesh:m,life:0});}
 }
 makeSkater(id){const g=new THREE.Group(),color=SKATERS.find(c=>c.id===id)?.color||'#5276a5';this.mesh(g,0,.16,0,.5,.13,1.65,color);for(const x of [-.29,.29])for(const z of [-.55,.55])this.mesh(g,x,.12,z,.1,.12,.12,'#b1dfbd','sphere');if(id==='pigeon'){this.mesh(g,0,.7,0,.45,.55,.7,'#909caa','sphere');this.mesh(g,0,1.1,-.4,.27,.32,.3,'#a6b6b4','sphere');this.mesh(g,0,1.08,-.72,.12,.1,.2,C.amber);this.mesh(g,0,.9,.1,.7,.1,.6,'#8590a1');}else{this.mesh(g,-.15,.6,-.38,.24,.75,.25,'#343a56');this.mesh(g,.15,.6,.35,.24,.75,.25,'#343a56');this.mesh(g,0,1.25,0,.65,.8,.45,color);this.mesh(g,0,1.98,-.05,.42,.48,.4,'#d7ad88');this.mesh(g,0,2.23,-.06,.5,.12,.5,color);this.mesh(g,-.52,1.3,-.1,.6,.22,.23,'#d7ad88');this.mesh(g,.52,1.3,.1,.6,.22,.23,'#d7ad88');}return g;}
 buildRug(s){
  for(let i=0;i<8;i++){for(const side of [-1,1]){this.mesh(this.root,side*33.8,3,25-i*14,.12,2.5,8,s.world.spec.accent);this.mesh(this.root,side*33.6,5.4,25-i*14,.15,.12,10,C.cyan,'box',true);}this.mesh(this.root,0,9,25-i*14,68,.6,.6,'#293b45');}
  if(s.level===1){for(const side of [-1,1]){this.mesh(this.root,side*10,1.1,-28,.35,2.2,48,'#91d6c9');for(let i=0;i<4;i++)this.mesh(this.root,side*10,3.1,-8-i*12,.5,6,.5,'#7fb0b5','cylinder');}this.label(this.root,'DEEP END / 100X',0,8,-48,'#b7ffde');}
  if(s.level===3){for(let i=0;i<6;i++)this.mesh(this.root,i%2?-29:29,6,16-i*18,1.2,1.2,18,'#9c6fc2','cylinder');}
  if(s.level===7){for(let i=0;i<14;i++){this.mesh(this.root,i%2?-29:29,1.7,25-i*8,2,3,2,'#bfa857','cylinder');}}
  for(const item of s.world.pickups){const g=new THREE.Group();g.position.set(item.x,item.y+.5,item.z);this.mesh(g,0,0,0,.7,.7,.7,item.type==='health'?C.mint:item.type==='armor'?C.cyan:C.amber,'sphere',true);this.root.add(g);this.dynamic.set(item.id,g);}
  for(const item of [...s.world.switches,...s.world.secrets]){const g=this.mesh(this.root,item.x,item.y+1,item.z,item.w||1.1,1.6,.5,item.secret?'#7e6994':C.cyan,'box',!item.secret);this.dynamic.set(item.id,g);if(!item.secret)this.label(this.root,item.label,item.x,item.y+3,item.z,'#86ffe0',.55);}
  const exit=s.world.exit;this.exit=this.mesh(this.root,exit.x,exit.y+2,exit.z,3,4,.25,C.mint,'box',true);this.label(this.root,'EXIT / E',exit.x,exit.y+5,exit.z,'#b0ff88',.65);
  this.enemyMeshes=new Map();this.lasers=new Map();this.projectileMeshes=[];for(let i=0;i<128;i++){const m=this.mesh(this.scene,0,-100,0,.2,.2,.2,C.amber,'sphere',true);m.visible=false;this.projectileMeshes.push(m);}
  this.crates=[];for(let i=0;i<12;i++){const m=this.mesh(this.scene,0,-100,0,2,2,2,'#a0b2a3');m.visible=false;this.crates.push(m);}
  this.zones=[];for(let i=0;i<12;i++){const m=this.mesh(this.scene,0,-100,0,1,.06,1,'#dc5271','cylinder',true);m.visible=false;this.zones.push(m);}
  this.weapon=new THREE.Group();this.camera.add(this.weapon);this.scene.add(this.camera);this.mesh(this.weapon,.32,-.3,-.65,.16,.2,.5,'#4a5b68');this.mesh(this.weapon,.32,-.2,-.95,.11,.1,.4,'#b2d6c5');this.muzzle=this.mesh(this.weapon,.32,-.2,-1.2,.17,.17,.18,C.amber,'sphere',true);
  this.bag=this.mesh(this.weapon,.32,-.25,-.8,.65,.55,.5,'#b9a26f','sphere');this.bag.visible=false;this.heavyBarrel=this.mesh(this.weapon,.32,-.2,-.85,.3,.3,.7,'#7ba6a4','cylinder');this.heavyBarrel.rotation.x=Math.PI/2;this.heavyBarrel.visible=false;
  this.dev=this.makeEnemy({type:'dev',color:'#d7e4dd'});this.dev.position.set(s.world.exit.x,0,s.world.exit.z-3);this.scene.add(this.dev);
 }
 makeEnemy(e){const g=new THREE.Group(),color=e.color||'#dd7d7d',size=e.type==='whale'?2:e.type==='bagholder'?1.4:1;this.mesh(g,0,.9,0,.9*size,1.2*size,.7*size,color);this.mesh(g,0,1.65*size,0,.7*size,.5*size,.55*size,'#293943');this.mesh(g,0,1.65*size,.3*size,.48*size,.18*size,.06,C.mint,'box',true);for(const x of [-.3,.3])this.mesh(g,x*size,.25,0,.23,.5,.23,'#859596');if(['influencer','manager'].includes(e.type))this.mesh(g,0,2.2,0,.6,.7,.6,C.amber,'cone');if(e.type==='sniper')this.mesh(g,.6,1,0,.2,.2,2,'#858aaa');return g;}
 resize(){const {width,height}=this.canvas.getBoundingClientRect();if(width&&height){this.renderer.setSize(width,height,false);this.camera.aspect=width/height;this.camera.updateProjectionMatrix();}}
 draw(s,{debug=false,ghost=null}={}){
  const p=s.player;this.debug.visible=debug;
  if(s.kind==='mall'){
   this.skater.position.set(p.x,p.y+.08,p.z);if(s.character!=='pigeon'){this.skater.children[5].rotation.x=Math.sin(s.tick*.18)*Math.min(.28,Math.abs(p.speed)/70);this.skater.children[6].rotation.x=-this.skater.children[5].rotation.x;this.skater.children[10].rotation.z=.5+(p.grounded?0:.7);this.skater.children[11].rotation.z=-.5-(p.grounded?0:.7);}this.skater.children[0].rotation.z=!p.grounded&&s.combo.last.includes('FLIP')?s.tick*.3:0;
   this.skater.rotation.set(p.bail?Math.PI/2:p.grounded?0:Math.sin(s.tick*.2)*.12,p.yaw+(p.grounded?0:p.spin),p.rail?.08:0);
   const desired=new THREE.Vector3(p.x-Math.sin(p.yaw)*9,p.y+5.5,p.z+Math.cos(p.yaw)*9);if(!this.ready){this.camera.position.copy(desired);this.ready=true;}else this.camera.position.lerp(desired,.4);if(this.camera.position.distanceTo(desired)>5)this.camera.position.copy(desired);this.camera.lookAt(p.x+Math.sin(p.yaw)*3,p.y+1.2,p.z-Math.cos(p.yaw)*3);
   for(const o of s.world.props){const m=this.dynamic.get(o.id);m.scale.y=o.broken?.12:1;m.rotation.z=o.broken?.13:0;}
   for(const t of s.world.tapes){const m=this.dynamic.get(`tape-${t.id}`);m.visible=!s.tapes.includes(t.id);m.rotation.y=s.tick*.035;}
   for(const [i,g]of this.guards.entries()){const a=s.guards[i];g.visible=!!a;if(a){g.position.set(a.x,a.y,a.z);g.rotation.y=Math.atan2(p.x-a.x,p.z-a.z);g.scale.setScalar(a.cart?1.5:1);}}
   this.gate.visible=s.alert>=4;this.rugHole.visible=s.event?.type==='RUG';this.ambient.intensity=s.event?.type==='POWER OUTAGE'?.35:2;this.sun.intensity=s.event?.type==='POWER OUTAGE'?.2:2.1;
   for(const [i,actor]of this.eventActors.entries()){actor.visible=['BULL RUN','MALL WALKERS','GAS WAR'].includes(s.event?.type);if(actor.visible){actor.position.set(s.event.type==='MALL WALKERS'?(i-4)*3:s.event.type==='GAS WAR'?42+i:0,0,(s.tick%600)/600*150-75);actor.scale.setScalar(s.event.type==='BULL RUN'&&i===0?3:1);if(s.event.type==='BULL RUN'&&i>0)actor.visible=false;}}
   if(s.events.some(e=>['smash','special'].includes(e.type))&&this.particleTick!==s.tick){this.particleTick=s.tick;for(const [i,particle]of this.particles.entries()){particle.life=30;particle.mesh.position.set(p.x,p.y+1,p.z);particle.vx=Math.sin(i*2.4)*.15;particle.vz=Math.cos(i*2.4)*.15;particle.vy=.12+(i%5)*.04;particle.mesh.material=this.mat(s.character==='pigeon'?'#f6ffbb':C.amber);}}
   for(const particle of this.particles){particle.mesh.visible=particle.life>0;if(particle.life>0){particle.life--;particle.mesh.position.x+=particle.vx;particle.mesh.position.z+=particle.vz;particle.mesh.position.y+=particle.vy;particle.vy-=.009;}}

   this.ghost.visible=!!ghost?.length;if(this.ghost.visible){const f=ghost[Math.min(ghost.length-1,Math.floor(s.tick/6))];this.ghost.position.set(f[1],f[2],f[3]);this.ghost.rotation.y=f[4];}
   this.scene.fog.color.set(s.event?.type==='FLASH CRASH'?'#411d2a':s.event?.type==='POWER OUTAGE'?'#050d12':'#182329');
  }else{
   this.camera.position.set(p.x,p.y+(p.crouch?.75:1.65),p.z);this.camera.rotation.order='YXZ';this.camera.rotation.y=p.yaw;this.camera.rotation.x=p.pitch;
   const aliveIds=new Set(s.enemies.map(e=>e.id));for(const [id,mesh]of this.enemyMeshes)if(!aliveIds.has(id)){this.scene.remove(mesh);this.enemyMeshes.delete(id);const laser=this.lasers.get(id);if(laser){this.scene.remove(laser);this.lasers.delete(id);}}
   for(const e of s.enemies){let m=this.enemyMeshes.get(e.id);if(!m){m=this.makeEnemy(e);this.scene.add(m);this.enemyMeshes.set(e.id,m);}m.visible=e.hp>0;m.position.set(e.x,e.y,e.z);m.rotation.y=Math.atan2(p.x-e.x,p.z-e.z);if(e.telegraph>0&&!this.reducedMotion)m.scale.setScalar(1+.08*Math.sin(s.tick*.4));else m.scale.setScalar(1);if(e.type==='sniper'){let laser=this.lasers.get(e.id);if(!laser){laser=this.mesh(this.scene,0,0,0,.025,1,.025,0xff7777,'cylinder',true);this.lasers.set(e.id,laser);}laser.visible=e.hp>0&&e.telegraph>0;if(laser.visible){const a=new THREE.Vector3(e.x,e.y+1.5,e.z),b=new THREE.Vector3(p.x,p.y+1,p.z),d=b.clone().sub(a);laser.position.copy(a.add(b).multiplyScalar(.5));laser.scale.set(.025,d.length(),.025);laser.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());}}}
   for(const item of s.world.pickups){let m=this.dynamic.get(item.id);if(!m){m=this.mesh(this.root,item.x,item.y+.5,item.z,.7,.7,.7,C.mint,'sphere',true);this.dynamic.set(item.id,m);}m.visible=!item.taken;m.rotation.y=s.tick*.025;}
   for(const o of s.world.solids){const m=this.dynamic.get(o.id);if(m)m.visible=!o.broken;}
   for(const [i,m]of this.projectileMeshes.entries()){const b=s.projectiles[i];m.visible=!!b;if(b)m.position.set(b.x,b.y,b.z);}
   for(const [i,m]of this.crates.entries()){const h=s.hazards[i];m.visible=!!h?.friendly;if(m.visible)m.position.set(h.x,h.y+Math.max(1,h.delay*.2),h.z);}
   for(const [i,m]of this.zones.entries()){const z=s.hazards[i];m.visible=!!z;if(z){m.position.set(z.x,z.y+.04,z.z);m.scale.set(z.radius,.06,z.radius);m.material=this.mat(z.delay>0?0xe5b956:z.friendly?C.cyan:0xdc5271,true);}}
   this.bag.visible=s.weapon===6;this.weapon.children[0].visible=s.weapon!==6;this.weapon.children[1].visible=s.weapon!==6;this.heavyBarrel.visible=[2,3,4,5,7].includes(s.weapon);
   this.weapon.position.y=!this.reducedMotion?Math.sin(s.tick*.16)*.015*Math.min(1,Math.hypot(p.vx,p.vz)/10):0;this.weapon.position.z=s.shotFlash>0?.08:0;this.weapon.children[0].material=this.mat(s.weapon===1?'#e0a67c':s.weapon===2?'#92dbb5':'#8fa8b0');this.muzzle.visible=s.shotFlash>0;this.exit.material=this.mat(s.exitOpen?C.mint:0x884753,true);this.exit.position.set(s.world.exit.x,s.world.exit.y+2,s.world.exit.z);this.dev.visible=s.level===7||s.tick<600||s.escape;this.dev.position.z=s.level===7?-84:-8-Math.min(70,s.tick/8);this.dev.position.y=s.escape?Math.min(20,s.escape/30):0;
   for(const f of s.world.floors){const m=this.dynamic.get(f.id);if(m){m.position.y=s.escape&&f.z<s.collapseZ?-Math.min(50,(s.collapseZ-f.z)*2):(f.renderOffset||0);if(f.id==='pool-water'){m.visible=!s.world.switches.every(a=>a.used);}}}
   for(const item of s.world.switches){const m=this.dynamic.get(item.id);m.material=this.mat(item.used?0x547860:C.cyan,true);}
  }
  const direction=this.camera.getWorldDirection(new THREE.Vector3());for(const label of this.labels){const delta=label.getWorldPosition(new THREE.Vector3()).sub(this.camera.position);label.visible=delta.dot(direction)>8&&delta.length()<95;}
  this.renderer.render(this.scene,this.camera);
 }
 dispose(){this.scene.traverse(o=>{if(o.isMesh&&o.material?.map&&!this.disposables.includes(o.material.map))o.material.map.dispose();});for(const g of this.geometries.values())g.dispose();for(const m of this.materials.values())m.dispose();for(const d of this.disposables)d.dispose();this.renderer.dispose();}
}
