import Head from 'next/head';
import {useState} from 'react';
import CampaignShell from '../../components/arcade/CampaignShell';
import {TRACKS,VEHICLES} from '../../lib/arcade/race-sim.mjs';
import s from '../../styles/Campaign.module.css';
export default function CampaignAdmin(){
  const [token,setToken]=useState(''),[data,setData]=useState(null),[draft,setDraft]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState({userId:'',status:'review',reason:''});
  const request=async(path,body)=>{const r=await fetch('/api/campaign/admin'+path,{method:body?'POST':'GET',headers:{'X-Campaign-Admin':token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const result=await r.json();if(!r.ok)throw new Error(result.error);return result;};
  const load=async()=>{setError('');setBusy(true);try{const next=await request('');setData(next);setDraft(next.config);}catch(e){setError(e.message);}finally{setBusy(false);}};
  const update=(key,value)=>setDraft(d=>({...d,[key]:value}));
  const dateValue=ms=>ms?new Date(ms-new Date(ms).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
  const date=(label,key)=><label key={key}>{label}<input type='datetime-local' value={dateValue(draft[key])} onChange={e=>update(key,e.target.value?new Date(e.target.value).getTime():0)}/></label>;
  const save=async e=>{e.preventDefault();setBusy(true);setError('');try{await request('/settings',{config:draft});setNotice('Campaign settings saved and audited.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
  const exportAddresses=async()=>{setBusy(true);setError('');try{const result=await request('/addresses');const csv='address,chain_id,updated_at\n'+result.addresses.map(row=>[row.address,row.chain_id,new Date(row.updated_at).toISOString()].join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const link=document.createElement('a');link.href=url;link.download=`terminl-${result.frozen?'frozen':'draft'}-addresses.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice(`${result.addresses.length} qualified addresses exported (${result.frozen?'submission window frozen':'draft — submissions can still change'}). This does not publish an onchain allowlist.`);}catch(e){setError(e.message);}finally{setBusy(false);}};
  const reviewUser=async e=>{e.preventDefault();setBusy(true);setError('');try{await request('/review',review);setNotice('Review decision saved and audited.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <CampaignShell><Head><title>Campaign admin — TERMINL</title><meta name='robots' content='noindex,nofollow'/></Head><h1 className={s.title}>Campaign controls.</h1>
    {!data?<form className={s.card} onSubmit={e=>{e.preventDefault();void load();}}><label>CAMPAIGN ADMIN TOKEN<input type='password' value={token} onChange={e=>setToken(e.target.value)} autoComplete='off' required/></label><button className={s.primary} disabled={busy}>OPEN DASHBOARD</button><p className={s.fine}>The token stays in memory for this page. It is not saved in browser storage.</p></form>:<>
      <p className={s.notice}>X identity: {data.oauthReady?'configured':'not configured — activation blocked'}. Dates below use your local timezone. Access is pool eligibility; no guaranteed allocation is advertised.</p>
      <div className={s.adminGrid}><form className={s.card} onSubmit={save}><h2>Campaign and target</h2><label className={s.check}><input type='checkbox' checked={draft.active} onChange={e=>update('active',e.target.checked)}/>Open official qualification</label>
        <label>Campaign name<input value={draft.name} onChange={e=>update('name',e.target.value)} maxLength={60} required/></label>
        {date('Qualification starts','startsAt')}{date('Qualification ends (blank = no scheduled end)','endsAt')}
        <label>Track<select value={draft.track} onChange={e=>update('track',e.target.value)}>{Object.values(TRACKS).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
        <label>Player car<select value={draft.vehicle} onChange={e=>update('vehicle',e.target.value)}>{Object.values(VEHICLES).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label>
        <label>Barry’s car<select value={draft.botVehicle} onChange={e=>update('botVehicle',e.target.value)}>{Object.values(VEHICLES).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label>
        <label>Barry’s pace (0.55–1.10)<input type='number' min='.55' max='1.1' step='.01' value={draft.botPace} onChange={e=>update('botPace',Number(e.target.value))}/></label>
        <label>Time limit in seconds<input type='number' min={30} max={300} value={draft.targetSeconds} onChange={e=>update('targetSeconds',Number(e.target.value))}/></label>
        <label>Qualified pool capacity<input type='number' min={1} max={100000} value={draft.capacity} onChange={e=>update('capacity',Number(e.target.value))}/></label>
        {date('Address submission opens','addressStartsAt')}{date('Address submission closes / freezes','addressEndsAt')}
        <label>Optional announcement URL<input type='url' value={draft.announcementUrl} onChange={e=>update('announcementUrl',e.target.value)} placeholder='https://x.com/…'/></label>
        <button className={s.primary} disabled={busy}>SAVE SETTINGS</button><p className={s.fine}>New settings apply to new attempts. Runs already issued keep their recorded challenge rules.</p>
      </form><div><section className={s.card}><h2>Last 30 days</h2><button className={s.secondary} onClick={exportAddresses} disabled={busy}>EXPORT QUALIFIED ADDRESSES</button><div className={s.tableWrap}><table className={s.table}><thead><tr><th>EVENT</th><th>TOTAL</th><th>PLAYERS</th></tr></thead><tbody>{data.funnel.map(e=><tr key={e.name}><td>{e.name}</td><td>{e.total}</td><td>{e.players}</td></tr>)}</tbody></table></div><p className={s.fine}>Views and share clicks are deduplicated per browser/day. A share click is not proof of a published post. Qualification events come from verified server records.</p></section>
        <form className={s.card} onSubmit={reviewUser} style={{marginTop:20}}><h2>Review a qualification</h2><label>X user ID<input value={review.userId} onChange={e=>setReview({...review,userId:e.target.value})} required/></label><label>Decision<select value={review.status} onChange={e=>setReview({...review,status:e.target.value})}><option value='review'>Under review</option><option value='qualified'>Approve (capacity checked)</option><option value='banned'>Suspend</option></select></label><label>Audit reason<input value={review.reason} onChange={e=>setReview({...review,reason:e.target.value})} minLength={5} maxLength={300} required/></label><button className={s.secondary} disabled={busy}>SAVE REVIEW</button></form></div></div>
      <div className={s.sectionHeading}><h2>Recent players</h2><button className={s.secondary} onClick={load} disabled={busy}>REFRESH</button></div><div className={s.tableWrap}><table className={s.table}><thead><tr><th>X ID</th><th>HANDLE</th><th>ACCESS</th><th>ADDRESS</th></tr></thead><tbody>{data.users.map(u=><tr key={u.id}><td>{u.id}</td><td>@{u.username}</td><td>{u.qualification_status||'No qualification'}</td><td>{u.address||'Not submitted'}</td></tr>)}</tbody></table></div>
      <h2 className={s.sectionHeading}>Recent audit trail</h2><div className={s.tableWrap}><table className={s.table}><thead><tr><th>TIME</th><th>ACTOR</th><th>ACTION</th><th>DETAIL</th></tr></thead><tbody>{data.audit.map(a=><tr key={a.id}><td>{new Date(a.at).toLocaleString()}</td><td>{a.actor}</td><td>{a.action}</td><td><details><summary>VIEW</summary><pre>{JSON.stringify(JSON.parse(a.detail),null,2)}</pre></details></td></tr>)}</tbody></table></div>
      <button className={s.textButton} onClick={()=>{setToken('');setData(null);setDraft(null);}}>LOCK DASHBOARD</button>
    </>}
    {error&&<p role='alert' className={s.error}>{error}</p>}{notice&&<p role='status' className={s.notice}>{notice}</p>}
  </CampaignShell>;
}
