import Head from 'next/head';
import CampaignShell from '../components/arcade/CampaignShell';
import s from '../styles/Campaign.module.css';
export default function ArcadePrivacy(){return <CampaignShell><Head><title>Arcade privacy and access rules — TERMINL</title></Head><h1 className={s.title}>What we save. What you earn.</h1>
  <section className={s.card}><h2>Play before signing in.</h2><p>Official attempts use an anonymous browser cookie. We save the race setup, verified result and basic campaign events so we can verify wins, handle duplicate claims and measure whether people enjoy the challenge.</p>
    <h2>X saves your identity.</h2><p>After a win, you can use X to save it to your Arcade Pass. We store your X user ID, handle and display name. Your immutable user ID prevents a handle change from creating another qualification.</p><p>The X authorization asks for the read scopes required for identity lookup. We only retrieve your profile. We do not read your posts or messages, follow accounts, post for you or keep an X access token after sign-in.</p>
    <h2>You choose whether your handle is public.</h2><p>Public cards and leaderboard entries show ANON unless you opt to display your X handle. You can change that setting on your Arcade Pass. A shared link can be copied by others, and social platforms may keep earlier previews.</p>
    <h2>Qualification is pool eligibility.</h2><p>One verified official win can qualify an X account to register for the pre-mint pool while the campaign is open and capacity remains. Suspicious results may require review. A full pool is shown as a waitlist. Neither a win nor an address submission guarantees an NFT, a mint allocation or financial returns.</p>
    <h2>Referrals need real wins.</h2><p>A referral counts when a new, distinct X account arrives through a challenge link, beats the official target and saves an accepted qualification. Self-referrals, repeat claims, clicks and unsaved runs do not count. Invalidated qualifications lose their referral credit.</p>
    <h2>Addresses come later.</h2><p>During the published address window, qualified players can paste one public Robinhood Chain mainnet address and edit it until the deadline. One address can be registered to one X identity. We keep an edit history. No wallet connection, signature, token approval or payment is part of registration.</p>
    <h2>Anti-abuse and storage.</h2><p>We use short-lived request limits, replay fingerprints and duplicate-claim signals to protect the campaign. Qualification, public-address records and admin changes are stored on the arcade service. Your wallet balances, holdings, private keys, DMs and contacts are not collected by this flow.</p>
  </section></CampaignShell>;}
