import Head from 'next/head';
import CampaignShell from '../components/arcade/CampaignShell';
import s from '../styles/Campaign.module.css';
export default function ArcadePrivacy(){return <CampaignShell><Head><title>Arcade privacy and WL rules — TERMINL</title></Head><h1 className={s.title}>What we save. What you earn.</h1>
  <section className={s.card}><h2>Play before signing in.</h2><p>Official runs use an anonymous browser cookie. We save each run’s setup, the inputs needed to verify each race or fight, the verified results and basic campaign events, so we can check wins, handle duplicate claims and measure whether people enjoy the challenge.</p>
    <h2>You choose the identity.</h2><p>After completing a route, or any time you want to check your pass, you can sign in with X, Farcaster or Discord. We store the provider, its immutable account ID and the public name needed for your Arcade Pass. We request no email. X and Discord tokens are discarded after lookup; Farcaster supplies a signed identity message that we verify and do not use to access a wallet.</p><p>We do not read posts or messages, follow accounts, join servers, post for you or keep social access tokens after sign-in.</p>
    <h2>You choose whether your identity is public.</h2><p>Public cards and leaderboard entries show ANON unless you opt to display your handle or Farcaster ID. You can change that setting on your Arcade Pass. A shared link can be copied by others, and social platforms may keep earlier previews.</p>
    <h2>WL spots are FCFS, not GTD.</h2><p>There are two routes, and each earns one WL spot per identity: beat BarryBot on points across the six-race Barry Cup in Wen Lambo, or win all six fights of one official Rekt Rumble circuit. Spots are first come, first served: they are confirmed in the order completed runs are saved, while the pool has room. A full pool is shown as a waitlist. An FCFS WL spot lets you mint during the WL phase while supply lasts. It is not a guaranteed (GTD) allocation, and neither a spot nor an address submission reserves an NFT or promises financial returns. Suspicious results may be reviewed before a spot is confirmed. Wins saved under the original single-race challenge remain honored.</p>
    <h2>Points rank the leaderboard.</h2><p>Signed-in players earn arcade points from verified official runs: race wins and cup wins in the Barry Cup, fight wins and circuit clears in Rekt Rumble. Runs played before you sign in on the same browser are added when you sign in. Points decide leaderboard order only; they do not change WL spots.</p>
    <h2>Referrals need real wins.</h2><p>A referral counts when a new, distinct identity arrives through a challenge link, completes a route and saves a confirmed WL spot. Self-referrals, repeat claims, clicks and unsaved runs do not count. Spots that are invalidated lose their referral credit.</p>
    <h2>Addresses come later.</h2><p>During the published address window, players with a confirmed spot can paste one public Robinhood Chain mainnet address, which covers every spot on their pass, and edit it until the deadline. One address can be registered to one identity. We keep an edit history. No wallet connection, signature, token approval or payment is part of registration.</p>
    <h2>Anti-abuse and storage.</h2><p>We use short-lived request limits, replay fingerprints and duplicate-claim signals to protect the campaign. WL spots, points, public-address records and admin changes are stored on the arcade service. Your wallet balances, holdings, private keys, DMs and contacts are not collected by this flow.</p>
  </section></CampaignShell>;}
